version: '3'
services:
  node-back:
    image: node-back
    container_name: node-back
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      LOG_LEVEL: info
      DATABASE_URL: postgresql://postgres:P@ssw0rd@postgres:5432/new_Jira?schema=public
      JWT_END_TIME: 1h
      JWT_SECRET: x-auth-key
    depends_on:
      - postgres

  vue-app:
    image: vue-app
    container_name: vue-app
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      VUE_APP_URL: http://node-back:8080
    depends_on:
      - node-back

  postgres:
    image: postgres:13.1-alpine
    command: "postgres -c log_statement=all"
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: new_Jira
      POSTGRES_PASSWORD: P@ssw0rd

volumes:
  postgres_data: {}

