version: '3'
services:
  node_back:
    image: node_back
    container_name: node_back
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      SERVER_PORT: 80
      LOG_HUMAN_FRIENDLY: false
      LOG_LEVEL: info
      DATABASE_URL: postgresql://postgres:P@ssw0rd@postgres:5432/new_Jira?schema=public
      JWT_END_TIME: 1h
      JWT_SECRET: x-auth-key
    depends_on:
      - postgres

  vue-front:
    image: vue-front
    container_name: vue-front
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      VUE_APP_URL: http://node_back:8080
    depends_on:
      - node_back

  postgres:
    image: postgres:13.1-alpine
    command: "postgres -c log_statement=all"
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: new_Jira
      POSTGRES_PASSWORD: P@ssw0rd

volumes:
  postgres_data: {}

